name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hello Baghdad"
      - name: multiple script
        run: |
          node -v
          npm -v
      - name: Python Commands
        run: |
          import platform 
          print(platform.processor())
        shell: python
